[package]
name = "dbc_damm"
version = "0.1.0"
description = "Solana Anchor program for Dynamic Bonding Curve and DAMM migration"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.29.0"

[features]
no-entrypoint = []
